### ISSUE TITLE
Add an option to change Ricochet port.

### ISSUE THREAD

**Issue by githubbantor** [ricochet-im/ricochet#520] opened 2017-01-20 23:18 UTC
Currently, Ricochet use static port number, allowing anyone to portscan it to know whether the target is using Ricochet or not. Related to this, some webadmins are using custom port number to serve webpages, such as http://example.com:1234/ .
So, why not allow user to change Ricochet port number?

> Possible new format
> ricochet:gcyukaewrgvfbeayfge?5899 (1)
> ricochet:!dtjyzbrwevrgfv6f55rfia75reev (2)

1 ... Simple, but anyone can know the port number easily.
2 ... If start with '!', assume it's a two-way hash. (decrypt(string))==array(gcyukaewrgvfbeayfge,5899)

**Comment by githubbantor** [comment] 2017-01-20 23:18
Tried for 120 seconds to get a connection to [scrubbed]:9878. Giving up. (waiting for rendezvous desc)

TCP 9878

**Comment by special** [comment] 2017-01-21 00:20
Duplicate of #102 -- see the discussion on that bug as well. Thoughts welcome :)

**Closed by special** 2017-01-21 00:20 UTC
