### ISSUE TITLE
Let Ricochet to remember last window position x,y

### ISSUE THREAD

**Issue by GitHubHatesTor** [ricochet-im/ricochet#471] opened 2016-10-29 01:17 UTC
Expected Result:
When I close Ricochet and start it later, Ricochet GUI will appear in last X,Y position.

Actual Result:
Ricochet always open in the center of the screen.

BTW, is John Brooks john.brooks@dereferenced.net or @ricochet-im are gone? They don't reply to my emails yet.
Also, is @special a member of ricochet developer? If so, consider showing [Ricochet member] tag or something.

**Comment by special** [comment] 2016-11-02 16:57
Duplicate of #310 -- please do a quick search on the issue tracker before filing issues that might already exist.

> BTW, is John Brooks john.brooks@dereferenced.net or @ricochet-im are gone? They don't reply to my emails yet.

That would be me. I don't know what emails you're referring to.

> Also, is @special a member of ricochet developer? If so, consider showing [Ricochet member] tag or something.

Looks like there is a "Ricochet IM member" tag on all of my comments.

**Closed by special** 2016-11-02 16:57 UTC
