### ISSUE TITLE
crash in remove buddy

### ISSUE THREAD

**Issue by ioerror** [ricochet-im/ricochet#390] opened 2016-03-21 19:58 UTC
I added a buddy and then tried a little while later to remove that same pending buddy. This results in a reproducable crash bug:

```
[36101.257700] PAX: execution attempt in: <stack>, 3fc45471000-3fc45496000 3fffffda000
[36101.257708] PAX: terminating task: /usr/bin-oz/ricochet(ricochet):2290, uid/euid: 1000/1000, PC: 000003fc454910c0, SP:
000003fc454911a8
[36101.257710] PAX: bytes at PC: 00 40 3c 15 c3 03 00 00 90 c3 3f 32 c3 03 00 00 b0 11 49 45
[36101.257721] PAX: bytes at SP-8: 000003c314f44000 000003c3323fc4e3 000003fc45491290 0000000000000000 0000000000000001
000003c314e007e8 000000000013609a 0000000000004000 0000039d2158509a 000003c3153c3008 000003c3153c3038
```

Second crash:

```
[36171.199238] PAX: execution attempt in: <stack>, 3fd92998000-3fd929bd000 3fffffda000
[36171.199245] PAX: terminating task: /usr/bin-oz/ricochet(ricochet):2462, uid/euid: 1000/1000, PC: 000003fd929b7f80, SP:
000003fd929b8068
[36171.199247] PAX: bytes at PC: 00 f0 a0 7c 1b 03 00 00 90 33 e4 99 1b 03 00 00 70 80 9b 92
[36171.199258] PAX: bytes at SP-8: 0000031b7c80e000 0000031b99e434e3 000003fd929b8150 0000000000000000 0000000000000001
                  0000031b7c7007e8 000000000013609a 0000000000004000 000002fa5604509a 0000031b7ca0e008 0000031b7ca0e038
```

I'm unable to remove this pending buddy. I'm using PaX as noted on SubgraphOS.

**Comment by ioerror** [comment] 2016-03-21 20:05
I also tried to remove it with the context menu to the same effect:
```
[36752.889233] PAX: execution attempt in: <stack>, 3ff5a3ae000-3ff5a3d3000 3fffffda000
[36752.889240] PAX: terminating task: /usr/bin-oz/ricochet(ricochet):2911, uid/euid: 1000/1000, PC: 000003ff5a3ce1b0, SP: 000003ff5a3ce298
[36752.889242] PAX: bytes at PC: 00 20 22 18 4e 03 00 00 90 13 95 2e 4e 03 00 00 a0 e2 3c 5a 
[36752.889252] PAX: bytes at SP-8: 0000034e111fc000 0000034e2e9514e3 000003ff5a3ce380 0000000000000000 0000000000000001 0000034e110007e8 000000000013609a 0000000000004000 000003379d4cd09a 0000034e18221008 0000034e18221038 
```

**Comment by special** [comment] 2016-03-23 05:16
Potentially a duplicate of #278

**Comment by rburchell** [comment] 2017-05-04 22:13
Let's consider it so, then, as I haven't seen any further reports.

**Closed by rburchell** 2017-05-04 22:13 UTC
