### ISSUE TITLE
XMPP+OMEMO for offline messages

### ISSUE THREAD

**Issue by obvio171** [ricochet-im/ricochet#356] opened 2016-02-22 13:42 UTC
Would it be possible to use XMPP federation to turn each client into an XMPP server (over hidden services like now) that talks to other users in their own servers using OMEMO for encryption?

**Comment by ZimTester** [comment] 2016-03-13 19:35
About offline messages:
Lol. And how do you think offline messages should be delivered in that case? OMEMO trying to deliver offline encrypted message to the server, so server can keep it and wait till contact will be online and then send it to him. But if your contact=server, then the "server" will be offline too :) So who will keep your offline message and waiting for your contact become online? No one. Except yourself - your client. What he is doing already.

About encryption:
There is no need to use OMEMO for encryption here with its huge overhead. And even XMPP is nonsense here. There are several more appropriate solutions for Ricochet, like conservative OTR, fresh Axolotl, or its custom rewritten implementation [Salamander protocol](https://github.com/SilentCircle/libsalamander), etc.
Extra overhead is a real problem for Ricochet because of not very fast Tor network and using 6 relays for hidden service circuits (instead of 3 when you're browsing regular Internet over Tor).

**Comment by graingert** [comment] 2016-04-07 16:06
@ZimTester I imagine people could run a pool of "offline message hidden services" then the client can randomly pick one as their "offline message hidden service". Messages can be sent to that delegated host, encrypted for the "care of" host.

**Comment by graingert** [comment] 2016-04-07 16:06
using XMPP is probably overkill though

**Comment by graingert** [comment] 2016-04-07 16:09
duplicate of #354

**Comment by special** [comment] 2017-01-16 00:29
Ricochet won't be using XMPP. Federation doesn't solve any offline messaging problems in Ricochet's serverless model: if every client runs its own server, it's still unable to receive messages while offline. Storing messages with mutual contacts has also been proposed, but that leaks social graph metadata.

**Closed by special** 2017-01-16 00:29 UTC
