### ISSUE TITLE
Feature request: make /me command work please?

### ISSUE THREAD

**Issue by mrphs** [ricochet-im/ricochet#212] opened 2015-07-13 20:29 UTC
Can we have legacy/old-skool chat commands like `/me` to work in ricochet please?

**Comment by s-rah** [comment] 2015-07-13 23:43
Linking to https://github.com/ricochet-im/ricochet/pull/197

**Comment by special** [comment] 2015-07-14 04:49
Duplicate of #13 and the PR #197.

**Closed by special** 2015-07-14 04:49 UTC
