### ISSUE TITLE
Build error on NetBSD/amd64 7.99.30 

### ISSUE THREAD

**Issue by alnsn** [ricochet-im/ricochet#433] opened 2016-06-11 19:45 UTC
Source pulled few minutes ago.

qmake prints many errors about translation files. I don't actually need them, is there any way to disable translations?

$ env PKG_CONFIG_PATH=/usr/pkg/lib/pkgconfig /usr/pkg/qt5/bin/qmake
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_en.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_it.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_es.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_da.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_pt_BR.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_de.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_bg.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_cs.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_fi.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_fr.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_ru.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_uk.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_tr.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_nl_NL.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_fil_PH.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_sv.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_pl.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_he.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_sl.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_zh.qm'
RCC: Warning: No resources in 'translation/embedded.qrc'.
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_en.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_it.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_es.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_da.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_pt_BR.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_de.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_bg.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_cs.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_fi.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_fr.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_ru.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_uk.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_tr.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_nl_NL.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_fil_PH.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_sv.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_pl.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_he.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_sl.qm'
RCC: Error in 'translation/embedded.qrc': Cannot find file 'ricochet_zh.qm'
RCC: Warning: No resources in 'translation/embedded.qrc'.

**Comment by afk11** [comment] 2016-08-05 16:57
Not sure if you got this fixed, but the solution was already mentioned in another issue: https://github.com/ricochet-im/ricochet/issues/184

**Comment by special** [comment] 2016-08-16 03:23
Duplicate of #184

**Closed by special** 2016-08-16 03:23 UTC
