### ISSUE TITLE
Refreshing statuses on demand

### ISSUE THREAD

**Issue by kolodziej** [ricochet-im/ricochet#253] opened 2015-08-20 10:01 UTC
It is understandable that Ricochet cannot retry to connect each *HS* which is disconnected every 5 seconds because it would create a lot of unnecessary trafiic in Tor. However sometimes when I want to talk to somebody and I'm waiting for him it would be good if I could check if he is connected more often. After some attempts of automatic connections, time between next trials increases to 15 minutes. Sometimes tt can be too long.

In my opinion adding *reconnect*, *refresh* or *retry* option to context menu of each contact on contacts' list would be enough. Optionally we can check more often contacts which has their *ContactWindow* opened.

**Comment by special** [comment] 2015-08-21 12:48
Duplicate of #207

**Closed by special** 2015-08-21 12:48 UTC
