### ISSUE TITLE
Typing circumflex accents

### ISSUE THREAD

**Issue by luc--** [ricochet-im/ricochet#428] opened 2016-06-02 21:25 UTC
It is currently impossible to type the caret in any text boxes of ricochet. However it is possible to enter it by copy-pasting it from another software.

**Comment by timkuijsten** [comment] 2016-06-02 21:36
I can type the literal `^` as well as stuff like `ê` `ô` etc. in the chat text box on OS X 10.11 (by using option-i + letter).

**Comment by LGD-Fr** [comment] 2016-06-02 22:39
Dead keys (êâôòó etc.) with an _azerty_ or _bépo_ keyboard layout on a GNU/Linux Fedora system do not work indeed with the version proposed to download.

**Comment by rburchell** [comment] 2016-06-03 06:33
Looks like a duplicate of https://github.com/ricochet-im/ricochet/issues/60 ?

**Comment by LGD-Fr** [comment] 2016-06-03 08:59
The 5e54a9e or v1.1.2 **version compiled on _my_ (fedora 23) system** with `qmake-qt5 && make` does **not** have this problem.

**However**, the https://ricochet.im/releases/1.1.2/ricochet-1.1.2-static-x86_64.tar.bz2 **version from the website** does **not work properly** with dead keys, as explained upper. What a pity…

It seems the linux-static build is the problem, not the code.

**Comment by special** [comment] 2016-11-04 00:46
Thanks for bringing this up and looking into it. You're right -- it is just the static builds, because of missing platforminputcontext plugins. I did a little digging and put notes on #60. This looks pretty easy to fix.

Closing this issue, watch #60 for further progress.

**Closed by special** 2016-11-04 00:46 UTC
