### ISSUE TITLE
OpenGL error for portable Ricochet in Windows (Virtualbox)

### ISSUE THREAD

**Issue by mubix** [ricochet-im/ricochet#90] opened 2014-09-18 13:01 UTC
Using Virtualbox, even after installing "Direct3D support". I received this message when trying to start Ricochet:
![ricochet_opengl](https://cloud.githubusercontent.com/assets/679319/4319919/4cff9350-3f32-11e4-98f6-f4aac38b4065.png)

After enabling "3D Acceleration" for the VM I was able to start Ricochet.

**Comment by special** [comment] 2015-04-14 05:06
Should be fixed in Ricochet 1.1.0, because of Qt 5.4 and the dynamicgl build. Can somebody test this?

**Comment by gjedeer** [comment] 2015-04-14 07:24
What's the correct URL for the executable?

This:
https://ricochet.im/releases/1.1.0/Ricochet-1.1.0.exe
starts an installer in some Cyryllic language (russian? ukrainian?),
then fails with the usual Qt error message.

**Comment by special** [comment] 2015-04-15 04:35
@gjedeer that is the correct URL. The installer should be using your system's configured language (both russian and ukranian are supported). Is it wrong?

I'm surprised you see the same error. Interesting.

**Comment by gjedeer** [comment] 2015-04-15 08:51
I don't read russian or ukrainian, the system locale was set to Poland. (whatever language that was, it used a different alphabet: Polish uses latin alphabet like English, so my installation experience was like "oh, i guess this button must be Next"). If there's some option in the installer setting installation language by geographic proximity, it shouldn't be enabled.

**Comment by badon** [comment] 2015-11-24 23:18
I have this problem on a Windows 7 system that doesn't support OpenGL (it has problems). I suggest that fancy graphics are irrelevant to the purpose of Ricochet, and that requirement should be eliminated before this issue is closed.

**Comment by special** [comment] 2017-01-15 23:14
If any issues remained here, they're likely fixed by #367

**Closed by special** 2017-01-15 23:14 UTC
Labels: bug, packaging

**Comment by gjedeer** [comment] 2017-01-16 17:45
I can confirm that Ricochet is now usable!
