### ISSUE TITLE
runtime error in release/Settings.moc

### ISSUE THREAD

**Issue by infinity0** [ricochet-im/ricochet#269] opened 2015-09-23 15:43 UTC
I'm trying to make a Debian package with `CONFIG+=release DEFINES+=RICOCHET_NO_PORTABLE` and getting this error, both with 1.1.1 and latest git:

```
$ ricochet
release/Settings.moc:101:28: runtime error: member access within address 0x60b00001f830 which does not point to an object of type 'QObjectData'
0x60b00001f830: note: object is of type 'QObjectPrivate'
 03 00 80 78  88 d8 e2 a9 2f 7f 00 00  20 5f 01 00 80 60 00 00  a0 02 0d 00 30 60 00 00  80 d0 cc a9
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'QObjectPrivate'
exit code 1
```

`strace` shows that ricochet is trying weird file names:

```
access("/usr/bin/ricochet_en_GB.qm", R_OK) = -1 ENOENT (No such file or directory)
access("/usr/bin/ricochet_en_GB", R_OK) = -1 ENOENT (No such file or directory)
access("/usr/bin/ricochet_en_gb.qm", R_OK) = -1 ENOENT (No such file or directory)
access("/usr/bin/ricochet_en_gb", R_OK) = -1 ENOENT (No such file or directory)
access("/usr/bin/ricochet_en.qm", R_OK) = -1 ENOENT (No such file or directory)
access("/usr/bin/ricochet_en", R_OK)    = -1 ENOENT (No such file or directory)
access("/usr/bin/ricochet_en.qm", R_OK) = -1 ENOENT (No such file or directory)
access("/usr/bin/ricochet_en", R_OK)    = -1 ENOENT (No such file or directory)
access("/usr/bin/ricochet_en.qm", R_OK) = -1 ENOENT (No such file or directory)
access("/usr/bin/ricochet_en", R_OK)    = -1 ENOENT (No such file or directory)
access("/usr/bin/ricochet_", R_OK)      = -1 ENOENT (No such file or directory)
access("/usr/bin/ricochet", R_OK)       = 0
```

**Comment by infinity0** [comment] 2015-09-23 16:40
Well, I get this with latest git even in portable mode i.e. `qmake` then `make`. :(

**Comment by infinity0** [comment] 2015-09-30 14:55
Looks like setting `-fsanitize=vptr` to `-fno-sanitize=vptr` makes things work, but it's unclear that this is the best solution.

**Comment by special** [comment] 2015-10-22 03:59
Whoa, I'm pretty sure I wrote a nice comment about this. Maybe it was in a dream.

This is definitely not a bug in Ricochet itself - it shows up here because Settings is the first QObject we construct and use in Ricochet's code.

I wasn't able to reproduce this with Qt 5.5 on Debian testing. It might have been fixed in newer versions of Qt - in which case, we should remember to turn on -fsanitize=vptr when we can.

This could use a little more investigation, especially if it's going to be happening for other people building on GCC 5.

**Comment by PowerKiller** [comment] 2016-01-25 07:40
It happens for me.

**Comment by special** [comment] 2016-01-25 17:34
@PowerKiller are you also on Debian testing? Is the build using gcc or clang? What is the output of 'g++ -v' (or clang if appropriate)? Are you using the system packages for Qt?

**Comment by PowerKiller** [comment] 2016-01-26 06:14
1) I'm on Kubuntu 15.10
2) It's using gcc
3) pk@pk-To-be-filled-by-O-E-M:/tmp$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.2.1-22ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2) 
4) Yes I am using system packages for Qt.

**Comment by infinity0** [comment] 2016-02-19 17:37
I removed the patch and it appears to be working fine now on Debian unstable. `qtbase5-dev` is now at version `5.5.1+dfsg-14`, what about you @PowerKiller ?

**Comment by PowerKiller** [comment] 2016-02-23 07:09
nah, it doesn't work for me tho.

**Comment by PowerKiller** [comment] 2016-02-23 07:09
I was away for a bit
and I don't usually login to GitHub.

**Comment by special** [comment] 2017-01-15 22:38
Closing this due to age, and because it seems to be working on Debian and some other GCC 5 platforms these days.

@PowerKiller or anyone else with this bug, please comment to reopen if this is still happening for you on updated systems.

**Closed by special** 2017-01-15 22:38 UTC
Labels: bug
