### ISSUE TITLE
Tray icon

### ISSUE THREAD

**Issue by kolodziej** [ricochet-im/ricochet#247] opened 2015-08-13 21:10 UTC
I have started developing tray icon for Ricochet. You can check progress at [on **tray-icon** branch of my fork](https://github.com/kolodziej/ricochet/tree/tray-icon). By now it can hide and show main window and show context menu with some actions on right click.

**Comment by special** [comment] 2015-09-11 00:28
Duplicate of #10

**Closed by special** 2015-09-11 00:28 UTC
