### ISSUE TITLE
Minimize to systray?

### ISSUE THREAD

**Issue by Paradoxum** [ricochet-im/ricochet#305] opened 2015-11-24 13:29 UTC
Could this be in a future release? it's pretty annoying closing the main window exits it.

Thanks

**Comment by 1ac0** [comment] 2015-12-04 12:55
+1

Should be nice to be able minimaze app to systray with notification on the new message arrive, thanks.

**Comment by kolodziej** [comment] 2015-12-23 23:42
This feature is in #260. This PR is waiting for merge since end of September.

**Comment by special** [comment] 2016-01-02 15:29
Duplicate of #260

**Closed by special** 2016-01-02 15:29 UTC
