### ISSUE TITLE
Add control socket

### ISSUE THREAD

**Issue by ioerror** [ricochet-im/ricochet#393] opened 2016-03-23 15:49 UTC
Ricochet should use `/var/run/tor/control` when `ricochet` is in the `debian-tor` user group on Debian Gnu/Linux rather than `127.0.0.1:9051` for control port access.

**Comment by special** [comment] 2016-11-04 02:47
This is implemented in the (not yet merged) unix branch under #225. If `TOR_CONTROL_SOCKET` is set in environment, it will be used.

Closing this as a duplicate of #224 and #225.

**Closed by special** 2016-11-04 02:47 UTC
