### ISSUE TITLE
Ricochet Offline Messages

### ISSUE THREAD

**Issue by VicCebedo** [ricochet-im/ricochet#399] opened 2016-04-07 07:04 UTC
I have a very quick question, fairly new to this.
If I am OFFLINE (like my laptop is shutdown),
can someone leave me a message?
If yes, can I read it the next time I'm online?
If no, I'd like to make that a suggestion.
Thanks!

**Comment by ttsda** [comment] 2016-04-07 14:42
This would be quite difficult to implement due to the way Ricochet works on a fundamental level.
There is no server that could hold your message for you until you logged in, as the messages are sent directly from the sender to the receiver.
Some kind of DHT would need to be implemented over the tor network that would store and relay the messages to the clients when they came online.

**Comment by dmS0Zq** [comment] 2016-04-07 15:17
You will get messages you missed when you come back online *if* the sender stays online the entire time.

**Comment by graingert** [comment] 2016-04-07 16:09
duplicate of #354

**Closed** 2016-04-08 09:16 UTC
